spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tg-bot
    username:
    password:
bot:
  api:
    key:
  name:
cbr:
  api:
    url: http://www.cbr.ru/dailyinfowebserv/dailyinfo.asmx?wsdl